# Generated by Django 5.2 on 2025-05-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculo', '0003_veiculo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=2)),
                ('descricao', models.TextField(max_length=200)),
                ('data', models.DateField(auto_now=True)),
                ('estaAtivo', models.BooleanField(default=True)),
                ('avaliacao', models.DecimalField(decimal_places=1, max_digits=1)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.veiculo')),
            ],
        ),
    ]
