# Generated by Django 5.2 on 2025-05-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_alter_anuncio_avaliacao_alter_anuncio_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(max_length=400),
        ),
    ]
