# Generated by Django 5.2 on 2025-05-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.SmallIntegerField(choices=[(1, 'PRETO'), (2, 'VERMELHO'), (3, 'AZUL'), (4, 'PRATA'), (5, 'BRANCO'), (6, 'VERDE'), (7, 'AZUL')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
    ]
